name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Code linting
        run: |
          # Add commands for code linting (e.g., flake8, pylint)

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker build and push
        run: |
          docker build -t your_dockerhub_username/your_image_name .
          docker push your_dockerhub_username/your_image_name
